# Site Settings
baseurl: ""

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
blog: True

# Language of the website
lang: en

# Search engine optimization settings
title: Yoav Rabinovich CV
tagline: Machine Learning Theory, Natural Language Processing, Quantum Computing.
description: Personal Website for Yoav Rabinovich
author: Yoav Rabinovich
twitter:
  username:
  card:
logo: /assets/img/smile.png
social:
  name: Yoav Rabinovich
  links:
    - https://github.com/Shesh6
locale: en_GB

# Page Settings
theme_settings:
  title: Yoav Rabinovich CV

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true


# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Rabinovich
  first_name: [Yoav, Y.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "6.2.1"
  integrity: "sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
